image: cimg/rust:1.45.0
stages:
  - build-node
  - build-contract
  - test-contract
  - deploy
  
  # Job's name
build-node:
  # Define stage
  stage: build-node
  # What to run on the job.
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends clang build-essential cmake libbz2-dev libclang-dev liblz4-dev librocksdb-dev libsnappy-dev libzstd-dev
  script:
    - cd nearlott
    - npm install
    
  artifacts:
    paths:
      - node_modules

contract-test-unit:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:unit
  artifacts:
    paths:
      - node_modules

contract-simulation-test:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:simulation
  artifacts:
    paths:
      - node_modules
