image: cimg/rust:1.56.1-node
stages:
  - build-node
  - test-contract
  - deploy
  
  # Job's name
build-node:
  # Define stage
  before_script:
    - rustup target add wasm32-unknown-unknown
    - apt-get update && apt-get install -y git less vim clang

  stage: build-node
  # What to run on the job.
  script:
    - cargo --version
    - node --version
    - cd nearlott
    - npm install
  
  artifacts:
      paths:
        - node_modules

contract-test-unit:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:unit
  artifacts:
    paths:
      - node_modules

contract-simulation-test:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:simulation
  artifacts:
    paths:
      - node_modules
