image: vibbioinfocore/rust-node-ci
stages:
  - build-node
  - build-contract
  - test-contract
  - deploy
  
  # Job's name
build-node:
  # Define stage
  stage: build-node
  # What to run on the job.
  script:
    - cd nearlott
    - npm install
  artifacts:
    paths:
      - node_modules

test-contract:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:unit
    - npm run test:integration
  artifacts:
    paths:
      - node_modules
