image: cimg/rust:1.45.0
stages:
  - build-node
  - build-contract
  - test-contract
  - deploy
  
  # Job's name
build-node:
  # Define stage
  stage: build-node
  # What to run on the job.
  script:
    - cd nearlott
    - npm install
    
  artifacts:
    paths:
      - node_modules

contract-test-unit:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:unit
  artifacts:
    paths:
      - node_modules

contract-simulation-test:
  stage: test-contract
  script:
    - cd nearlott
    - npm run build
    - npm run test:simulation
  artifacts:
    paths:
      - node_modules
